cc_binary(
    name = "cpp_web",
    srcs = ["src/main.cpp"],
    deps = [
        "//projects/cpp_calculator:calculator_lib",
        "//third_party/crow"
    ],
    includes = ["third_party/crow/include"]
)